### ISSUE TITLE
Injection Error: InnerMessage:Illegal characters in path.

### ISSUE THREAD

**Issue by ShauwnTheSheep** [hismightiness/dnnextensions#145]
Hello,
When I try to save my script I see the error below. Could you help me?
Thanks
Marco

--------------------------------------------------------------------------
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:c14797b9-f233-4c43-95e3-6aa06b7a613b
AssemblyVersion:7.4.2
PortalId:0
UserId:1
TabId:36
RawUrl:/home/ctl/Edit/mid/3650
Referrer:http://www.mywebsite.info/home/ctl/Edit/mid/3650
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
ExceptionHash:f0TaNEa1LWJjsfT0TZOhJA==
Message:Illegal characters in path.
StackTrace:
InnerMessage:Illegal characters in path.
InnerStackTrace:
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Web.InternalSecurityPermissions.PathDiscovery(String path)
   at System.Web.HttpRequest.MapPath(VirtualPath virtualPath, VirtualPath baseVirtualDir, Boolean allowCrossAppMapping)
   at System.Web.HttpServerUtility.MapPath(String path)
   at WillStrohl.Modules.Injection.EditInjections.cvContent_OnServerValidate(Object source, ServerValidateEventArgs args)
   at System.Web.UI.WebControls.CustomValidator.OnServerValidate(String value)
   at System.Web.UI.WebControls.CustomValidator.EvaluateIsValid()
   at System.Web.UI.WebControls.BaseValidator.Validate()
   at System.Web.UI.Page.Validate(String validationGroup)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.WebControls.LinkButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Nome Server:GENERICUK016

**Comment by hismightiness** [comment]
Hello:

Thank you for creating an issue.  I'm afraid I don't have enough information to really chime in yet.  Would you be able to supply the script and/or screenshots of how you were able to generate the error?  Until I can reproduce the issue myself, fixing it or offering advice will be difficult.

**Comment by WillStrohl** [comment]
Have you tried this in the most recent release(s)?  It may be resolved already.  😎
https://github.com/WillStrohl/dnnextensions/releases/tag/CI-03.02.00
