### ISSUE TITLE
Content Injection Module jnstallation error

### ISSUE THREAD

**Issue by TampaBayWater1998** [hismightiness/dnnextensions#173]
We're using Evoq Content 09.01.01 and are getting the following error when trying to install the module:

Failure SQL Execution resulted in following Exceptions: 
 System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.h2obj_syscolumns'.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:f3130308-275b-42b7-b0d9-aaefe33d8a61
 Error Number:208,State:1,Class:16
 
 /*
 
 INSTALL SQL PROVIDER SCRIPT
 
 Injection Module for DotNetNuke
 Version: 02.00.00
 Author: Will Strohl
 E-Mail: will.strohl@gmail.com
 Website: http://www.willstrohl.com
 
 Copyright 2009-2015 Will Strohl
 
 Release Notes:
 Added CustomProperties property.
 
 */
 
 IF NOT EXISTS (SELECT 1 FROM dbo.[h2obj_syscolumns] c JOIN dbo.[h2obj_sysobjects] o ON c.[id] = o.[id] WHERE c.[name] = N'custom_properties' AND o.[name] = 'h2obj_wns_inj_injection')
 ALTER TABLE dbo.[h2obj_wns_inj_injection] 
 ADD [custom_properties] NVARCHAR(MAX) NULL;
 
 System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'custom_properties'.
 Invalid column name 'custom_properties'.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:f3130308-275b-42b7-b0d9-aaefe33d8a61
 Error Number:207,State:1,Class:16
 
 UPDATE dbo.[h2obj_wns_inj_injection] 
 SET [custom_properties] = N'[]' 
 WHERE 
 [custom_properties] = N'' OR
 [custom_properties] IS NULL;
 
 System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'custom_properties'.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:f3130308-275b-42b7-b0d9-aaefe33d8a61
 Error Number:207,State:1,Class:16
 
 CREATE PROCEDURE dbo.[h2obj_wns_inj_AddInjectionContent] 
 @ModuleId INT, @InjectTop BIT, @InjectName NVARCHAR(50), @InjectContent NVARCHAR(MAX), @IsEnabled BIT, @OrderShown INT, @CustomProperties NVARCHAR(MAX) 
 AS 
 BEGIN 
 SET NOCOUNT ON
 INSERT INTO dbo.[h2obj_wns_inj_injection] ([module_id],[inject_top],[inject_name],[inject_content],[is_enabled],[order_shown],[custom_properties]) 
 VALUES (@ModuleId, @InjectTop, @InjectName, @InjectContent, @IsEnabled, @OrderShown, @CustomProperties)
 SELECT SCOPE_IDENTITY()
 END
 
 System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'custom_properties'.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:f3130308-275b-42b7-b0d9-aaefe33d8a61
 Error Number:207,State:1,Class:16
 
 CREATE PROCEDURE dbo.[h2obj_wns_inj_UpdateInjectionContent] 
 @InjectionId INT, @ModuleId INT, @InjectTop BIT, @InjectName NVARCHAR(50), @InjectContent NVARCHAR(MAX), @IsEnabled BIT, @OrderShown INT, @CustomProperties NVARCHAR(MAX) 
 AS
 BEGIN
 SET NOCOUNT ON
 UPDATE dbo.[h2obj_wns_inj_injection] SET 
 [module_id] = @ModuleId, 
 [inject_top] = @InjectTop, 
 [inject_name] = @InjectName, 
 [inject_content] = @InjectContent, 
 [is_enabled] = @IsEnabled, 
 [order_shown] = @OrderShown, 
 [custom_properties] = @CustomProperties
 WHERE [injection_id] = @InjectionId
 END
 
 System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'custom_properties'.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:f3130308-275b-42b7-b0d9-aaefe33d8a61
 Error Number:207,State:1,Class:16
 
 CREATE PROCEDURE dbo.[h2obj_wns_inj_GetInjectionContents] 
 @ModuleId INT 
 AS
 BEGIN
 SET NOCOUNT ON;
 
 SELECT wsi.[injection_id], wsi.[module_id], wsi.[inject_top], wsi.[inject_name], wsi.[inject_content], wsi.[is_enabled], wsi.[order_shown], wsi.[custom_properties] 
 FROM dbo.[h2obj_wns_inj_injection] wsi 
 WHERE wsi.[module_id] = @ModuleId 
 ORDER BY wsi.[order_shown], wsi.[inject_name];
 END
 
 System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'custom_properties'.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:f3130308-275b-42b7-b0d9-aaefe33d8a61
 Error Number:207,State:1,Class:16
 
 CREATE PROCEDURE dbo.[h2obj_wns_inj_GetInjectionContent] 
 @InjectionId INT 
 AS
 BEGIN
 SET NOCOUNT ON
 SELECT wsi.[injection_id], wsi.[module_id], wsi.[inject_top], wsi.[inject_name], wsi.[inject_content], wsi.[is_enabled], wsi.[order_shown], wsi.[custom_properties] 
 FROM dbo.[h2obj_wns_inj_injection] wsi 
 WHERE wsi.[injection_id] = @InjectionId
 END
 
 System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'custom_properties'.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:f3130308-275b-42b7-b0d9-aaefe33d8a61
 Error Number:207,State:1,Class:16
 
 CREATE PROCEDURE dbo.[h2obj_wns_inj_GetActiveInjectionContents] 
 @ModuleId INT 
 AS
 BEGIN
 SET NOCOUNT ON;
 
 SELECT wsi.[injection_id], wsi.[module_id], wsi.[inject_top], wsi.[inject_name], wsi.[inject_content], wsi.[is_enabled], wsi.[order_shown], wsi.[custom_properties] 
 FROM dbo.[h2obj_wns_inj_injection] wsi 
 WHERE wsi.[module_id] = @ModuleId AND wsi.[is_enabled] = 1 
 ORDER BY wsi.[order_shown], wsi.[inject_name];
 END

**Comment by shlaing** [comment]
By the way, Can you compile the source ? I can't loaded the project.

**Comment by WillStrohl** [comment]
Do you still have this issue in the most recent release?  I believe this is working in the most recent release, despite me not seeing this issue until now. 🫣 
https://github.com/WillStrohl/dnnextensions/releases/tag/CI-03.02.00
