### ISSUE TITLE
Content Injection Module breaks with DNN 7.4

### ISSUE THREAD

**Issue by mentomorph** [hismightiness/dnnextensions#63]
Hi,

After I upgraded from v7.3 to v7.4 a message "an module on this page is not working".
Uninstalled Content Injection Module and re-installed but the module wouldn't be injected into any page (please find the Exception below).
I've also tried rebuilding from source with new DotNetNuke.Web.dll and DotNetNuke.Web.Client.dll but the error remains the same when trying to add to a page.

Exception:
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:37b77497-f214-4e3c-9c14-7efa2b28a606
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:+WMZuRIna/Vv2KVyVZUbFw==
Message:Could not load type 'WillStrohl.Modules.Injection.InjectionController' from assembly 'WillStrohl.Modules.Injection'.
StackTrace:
   at DotNetNuke.UI.Utilities.Reflection.CreateType(String TypeName, String CacheKey, Boolean UseCache, Boolean IgnoreErrors)
   at DotNetNuke.UI.Skins.Pane.IsVesionableModule(ModuleInfo moduleInfo)
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
   at DotNetNuke.UI.Skins.Skin.InjectModule(Pane pane, ModuleInfo module)
InnerMessage:
InnerStackTrace:
Source:DotNetNuke.WebUtility
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name:

**Comment by hismightiness** [comment]
Are you able to do the build again, and run it in debug mode to give more information?

Also, does the DLL exist in the Bin and what is its file name?

**Comment by mentomorph** [comment]
Hi, I tried debugging the module but the exception happens in DNN before it's loaded, however the exception is slightly different now but still the same (probably since it's debug version). 
Yes, WillStrohl.Modules.Injection.dll is in Website\bin.


**Message**:Could not load type 'WillStrohl.Modules.Injection.InjectionController' from assembly 'WillStrohl.Modules.Injection'.
**StackTrace**'
   at DotNetNuke.UI.Utilities.Reflection.CreateType(String TypeName, String CacheKey, Boolean UseCache, Boolean IgnoreErrors)
   at DotNetNuke.UI.Utilities.Reflection.CreateType(String TypeName, String CacheKey, Boolean UseCache)
   at DotNetNuke.UI.Utilities.Reflection.CreateObject(String TypeName, String CacheKey, Boolean UseCache)
   at DotNetNuke.UI.Utilities.Reflection.CreateObject(String TypeName, String CacheKey)
   at DotNetNuke.UI.Skins.Pane.IsVesionableModule(ModuleInfo moduleInfo)
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
   at DotNetNuke.UI.Skins.Skin.InjectModule(Pane pane, ModuleInfo module)

**Comment by mentomorph** [comment]
Hi, I've found the bug in "WillStrohl.Injection.dnn". Namespace missmatch. Components was missing. Please find below corrected version.

File: WillStrohl.Injection.dnn
.....
```<component type="Module">
          <desktopModule>
            <moduleName>WillStrohl.Injection</moduleName>
            <foldername>WillStrohl.Injection</foldername>
            <businessControllerClass>WillStrohl.Modules.Injection.```**Components**```.InjectionController, WillStrohl.Modules.Injection</businessControllerClass>```
.....

Kr

**Comment by hismightiness** [comment]
You'll find a 2.0.1 release that fixes this issue.
