### ISSUE TITLE
CodeCamp: Saving task doesn't update task list quantities

### ISSUE THREAD

**Issue by hismightiness** [hismightiness/dnnextensions#97]

**Comment by hismightiness** [comment]
A new date/time issue has crept up...

Message:SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.
StackTrace:
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Glimpse.Ado.AlternateType.GlimpseDbCommand.ExecuteScalar()
   at PetaPoco.Database.ExecuteScalarHelper(IDbCommand cmd)
   at PetaPoco.DatabaseTypes.SqlServerDatabaseType.ExecuteInsert(Database db, IDbCommand cmd, String PrimaryKeyName)
   at PetaPoco.Database.Insert(String tableName, String primaryKeyName, Boolean autoIncrement, Object poco)
   at PetaPoco.Database.Insert(Object poco)
   at DotNetNuke.Data.RepositoryBase`1.Insert(T item)
   at WillStrohl.Modules.CodeCamp.Entities.VolunteerTaskInfoRepository.CreateItem(VolunteerTaskInfo i) in C:\Websites\Development\Modules\CodeCamp\Entities\VolunteerTaskInfoRepository.cs:line 43
   at WillStrohl.Modules.CodeCamp.Entities.VolunteerTaskInfoController.CreateItem(VolunteerTaskInfo i) in C:\Websites\Development\Modules\CodeCamp\Controllers\VolunteerTaskInfoController.cs:line 50
   at WillStrohl.Modules.CodeCamp.Services.EventController.CreateVolunteerTask(VolunteerTaskInfo task) in C:\Websites\Development\Modules\CodeCamp\Services\Controllers\VolunteerTaskController.cs:line 219
